name:                statix
version:             0.1.0.0
github:              "githubuser/statix"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/statix#readme>

dependencies:
- base >= 4.7 && < 5
- array
- mtl
- containers
- unordered-containers
- data-default
- unification-fd
- list-extras >= 0.4.1.4
- ansi-terminal
- directory
- filepath
- text
- union-find
- hashable
- haskeline

default-extensions:
- UnicodeSyntax
- PatternSynonyms
- LambdaCase
- FunctionalDependencies
- FlexibleInstances
- DuplicateRecordFields
- LambdaCase
- TypeFamilies
- FlexibleContexts
- TypeApplications
- MultiParamTypeClasses
- RankNTypes

library:
  source-dirs: src
  ghc-options:        
  - -fwarn-tabs
  - -fwarn-incomplete-patterns
  - -fwarn-incomplete-uni-patterns

executables:
  statix-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwarn-tabs
    - -fwarn-incomplete-patterns
    - -fwarn-incomplete-uni-patterns
    dependencies:
    - statix

tests:
  statix-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - statix
    - hspec
