name:                statix
version:             0.1.0.0
github:              "ajrouvoet/ministatix.hs"
author:              Arjen Rouvoet, Hendrik van Antwerpen, Daniel Pelsmaeker, et al
maintainer:          "a.j.rouvoet@gmail.com"
copyright:           "2019 A.J. Rouvoet"

extra-source-files:
- README.md

description: Please see the README at https://github.com/ajrouvoet/ministatix.hs

dependencies:
- base >= 4.7 && < 5
- array
- mtl
- containers
- unordered-containers
- data-default
- unification-fd
- list-extras >= 0.4.1.4
- ansi-terminal
- directory
- filepath
- text
- union-find
- hashable
- haskeline
- lens

build-tools:
- alex
- happy

default-extensions:
- UnicodeSyntax
- PatternSynonyms
- LambdaCase
- FunctionalDependencies
- FlexibleInstances
- DuplicateRecordFields
- LambdaCase
- TypeFamilies
- FlexibleContexts
- TypeApplications
- MultiParamTypeClasses
- RankNTypes
- TemplateHaskell
- ScopedTypeVariables
- DeriveTraversable
- DeriveFunctor
- DeriveFoldable

library:
  source-dirs: src
  ghc-options:        
  - -fwarn-tabs
  - -fwarn-incomplete-patterns
  - -fwarn-incomplete-uni-patterns

executables:
  statix-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwarn-tabs
    - -fwarn-incomplete-patterns
    - -fwarn-incomplete-uni-patterns
    dependencies:
    - statix

tests:
  statix-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - statix
    - hspec
