#!/usr/bin/env sh
set -o errexit
set -o nounset
set -o pipefail
#set -o xtrace

DIRECTORY=$(cd `dirname $0` && pwd)
WORKDIR=$PWD

make -C "${DIRECTORY}" build
cd ${DIRECTORY} && stack exec statix --cwd "${WORKDIR}" -- "$@"
